name: ci
on: workflow_dispatch
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
jobs:
  build-app:
    name: Build application and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: java -version
      - run: mvn --version
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: maven-build
          path: target/*.jar

  build-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: maven-build
          path: target
      - run: docker version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
